
resources:
  - name: spring-java-app
    type: git
    source:
      uri: https://github.com/VijayalakshmiKumar02/spring-java-app.git
      branch: master
  - name: time
    type: time
    source:
      interval: 60s


jobs:
  - name: maven-package
    plan:
    - aggregate:
      - get: git-repo
        trigger: true
      - get: time
    - task: maven-package
      privileged: true
      file: spring-java-app/build.yml
   

#   - name: rename file
#     plan:
#     - aggregate:
#       - get: jar-file
#         trigger: true
#         passed: [maven-package]
#       - get: time
#     - task: rename-file
#       file: git-repo/pipeline/rename-file.yml
